include: package:lint/analysis_options_package.yaml

linter:
  rules:
    sort_pub_dependencies: false
    avoid_classes_with_only_static_members: false
    sort_child_properties_last: false
    directives_ordering: false