name: duration_picker
description: A time picker widget that can select both minutes and hours. Fork from flutter_duration_picker.
version: 1.1.1
homepage: https://github.com/juliansteenbakker/duration_picker

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0